---
 
 php_packages:
   - php72 
   - php72-php-fpm 
   - php72-php-gd 
   - php72-php-json 
   - php72-php-mbstring 
   - php72-php-mysqlnd 
   - php72-php-xml 
   - php72-php-xmlrpc 
   - php72-php-opcache
   - php72-php-cli
   - php72-php-mysql
   - php72-php-curl

...
