---
 
 - name: Download do código fonte do wordpress
   unarchive:
     src: https://wordpress.org/latest.zip
     dest: /var/www/html
     owner: nginx
     group: nginx
     remote_src: yes
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

 - name: Adicionando Permissões ao Diretório do Wordpress
   file:
     path: /var/www/html/wordpress
     owner: nginx
     group: nginx
     state: directory
     mode: 0775
     recurse: yes
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

 - name: Configuração da key do wordpress
   local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
   register: "wp_salt"
   become: no
   become_method: sudo
   args:
     warn: false
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

 - name: Copiando o template wp-config.php para o servidor
   template:
     src: wp-config.php
     dest: /var/www/html/wordpress
     force: yes
     owner: nginx
     group: nginx
   notify:
     - Restart php-fpm
     - Restart nginx
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

...
