---
 
 - name: Restart php-fpm
   systemd:
     name: php72-php-fpm
     state: restarted
     daemon_reload: yes

 - name: Restart nginx
   systemd:
     name: nginx
     state: restarted
     daemon_reload: yes

...
