---

 - name: Start Nginx
   systemd:
     name: nginx
     state: started
     enabled: yes

 - name: Restart Nginx
   systemd:
     name: nginx
     state: restarted
     daemon_reload: yes
     
...
